app:
  build: .
  volumes:
  - .:/app:rw
  links:
  - redis:redis
  - influx:influx
  ports:
   - "8500:8500"
   - "8888:8888"
  environment:
  - RedisAddress=redis:6379
  - InfluxAddress=influx
  - InfluxDBName=events

redis:
  image: redis

influx:
  image: tutum/influxdb:0.9
  environment:
      - ADMIN_USER=root
      - INFLUXDB_INIT_PWD=root
      - PRE_CREATE_DB=events
  ports:
      - "8083:8083"
      - "8086:8086"

grafana:
  image: tutum/grafana
  links:
      - "influx:influx"
  ports:
    - "80:80"
  environment:
      - HTTP_USER=grafanauser
      - HTTP_PASS=grafanapass
      - INFLUXDB_PROTO=http
      - INFLUXDB_HOST=influx
      - INFLUXDB_PORT=8086
      - INFLUXDB_NAME=events
      - INFLUXDB_USER=root
      - INFLUXDB_PASS=root
      - INFLUXDB_IS_GRAFANADB=true