# provision.yml
---

- hosts: all
  tasks:
    - name: Add current Golang repo
      sudo: yes
      apt_repository: repo='ppa:ubuntu-lxc/lxd-stable'

    - name: Install essential packages
      sudo: yes
      apt:
        update_cache: yes
        name: "{{ item }}"
      with_items:
        - golang
        - vim
        - build-essential
        - git
        - unzip
        - supervisor
        - python-setuptools

    - name: Download AWS cfn-bootstrap
      sudo: yes
      get_url:
        url: https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
        dest: /usr/local/src/aws-cfn-bootstrap-latest.tar.gz

    - name: Prepare AWS cfn-bootstrap folder
      sudo: yes
      file:
        name: /usr/local/src/aws-cfn-bootstrap-latest
        state: directory

    - name: Extract AWS cfn-bootstrap
      sudo: yes
      shell: tar xvfz /usr/local/src/aws-cfn-bootstrap-latest.tar.gz --strip-components=1 -C /usr/local/src/aws-cfn-bootstrap-latest
      args:
        creates: /usr/local/src/aws-cfn-bootstrap-latest/setup.py

    - name: Install AWS cfn-bootstrap
      sudo: yes
      shell: easy_install /usr/local/src/aws-cfn-bootstrap-latest
      args:
        creates: /usr/local/bin/cfn-init

    - name: Ensure hoverfly-app user
      sudo: yes
      user:
        name: hoverfly-app
        shell: /bin/bash

    - name: Ensure hoverfly-app directory
      sudo: yes
      file:
        path: /home/hoverfly-app/go/src/github.com/SpectoLabs
        state: directory
        recurse: yes
        owner: hoverfly-app
        group: hoverfly-app

    - name: Ensure hoverfly-app log directory
      sudo: yes
      file:
        path: /home/hoverfly-app/logs
        state: directory
        recurse: yes
        owner: hoverfly-app
        group: hoverfly-app

    - name: Copy hoverfly-app from /tmp
      sudo: yes
      shell: "cp -R /tmp/hoverfly-app/ /home/hoverfly-app/go/src/github.com/SpectoLabs/; chown -R hoverfly-app:hoverfly-app /home/hoverfly-app/go/src/github.com/SpectoLabs/"
      args:
        creates: /home/hoverfly-app/go/src/github.com/SpectoLabs/hoverfly-app

    - name: Build hoverfly-app
      sudo: yes
      sudo_user: hoverfly-app
      command: "make build"
      environment:
        GOPATH: /home/hoverfly-app/go
      args:
        chdir: /home/hoverfly-app/go/src/github.com/SpectoLabs/hoverfly-app
        creates: /home/hoverfly-app/go/bin/hoverflyb

    - name: Create supervisor config
      sudo: yes
      shell: "cp /tmp/hoverfly-app/supervisor.conf /etc/supervisor/conf.d/hoverfly-app.conf"
      args:
        creates: /etc/supervisor/conf.d/hoverfly-app.conf
      notify:
        - Reread supervisor
        - Update supervisor

  handlers:
    - name: Reread supervisor
      sudo: yes
      command: supervisorctl reread

    - name: Update supervisor
      sudo: yes
      command: supervisorctl update